version: "3.9"

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: zinger_development
    ports:
      - "5432:5432"

  web:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/zinger_development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
